### ISSUE TITLE
Insert, Delete, Update implementations

### ISSUE THREAD

**Issue by franva** [supabase-community/sql-to-rest#6]
# Feature request
Insert, Delete, Update implementations

## Is your feature request related to a problem? Please describe.
I'm developing an app on the HarmonyOS Next platform, so I am not able to use any SDKs you provided, I have to rely on the DATA API to do CRUD. How can I do the Insert, Delete, Update etc. operations with DATA API?

## Describe the solution you'd like
All CRUD operations are supported via the DATA API in a Restful style or event a fully functional SDK for ArkTS. (Given the ArkTS is a superset of TypeScript, I hope this won't be too many troubles)

## Describe alternatives you've considered
N/A

## Additional context
![image](https://github.com/user-attachments/assets/266271b9-b387-4925-95f6-351b32f06e6d)

I was trying to use the SQL to REST API Translator to see all CRUD operations, when I was trying insert, it shows me this function has not been implemented.

**Comment by gregnr** [comment]
Hey @franva! Just to confirm, are you looking for the ability to do inserts, updates, and deletes directly with PostgREST (Supabase API) or are you looking to translate insert/update/delete SQL queries to PostgREST?

This library is specifically for translating SQL to PostgREST, so if all you're looking for is the ability to perform API inserts/updates/deletes, this is already possible:
- [inserts](https://docs.postgrest.org/en/v12/references/api/tables_views.html#insert)
- [updates](https://docs.postgrest.org/en/v12/references/api/tables_views.html#update)
- [deletes](https://docs.postgrest.org/en/v12/references/api/tables_views.html#delete)

Otherwise if you are looking for SQL translation for these operations, this is on the roadmap. We are happy to accept PRs!

**Comment by franva** [comment]
@gregnr 
Great! I also found it's possible to do the CRUD with the DATA API. But was not able to find the documentation. Thank you for your help.

No, SQL translation is not what I wanted. 

Just wondering with the DATA API(I guess the Restful API is called DATA API?), are we able to do all kinds of operations with PostgreSQL?

Are there any limitations for the DATA API?

Many thanks.

**Comment by gregnr** [comment]
Yes you can do most operations with PostgREST. There are some limitations for things like joins, but otherwise supports a large subset of SQL (in REST/HTTP syntax). I recommend checking out the [PostgREST docs](https://docs.postgrest.org/en/v12/references/api/tables_views.html) which are very detailed.

**Comment by franva** [comment]
thanks @gregnr . I have 2 questions, one is related to this, another is not.
I will create a separated issue.

So the DATA API(Restful API) comes from postgrest itself, not a Supabase thing, right? Any server which has configed PostgRest will support the API calls, right?
